const PEOPLE = [
  {
    animal: "dog",
    firstName: "Chris",
    middleName: "Mercutio",
    favoriteFood: "bacon",
    show: "The Wire",
  },
  {
    animal: "cat",
    firstName: "Loren",
    occupation: "developer",
    favoriteFood: "sushi",
    show: "Steven Universe",
  },
  {
    animal: "sloth",
    firstName: "Niki",
    occupation: "developer",
    middleName: "Esmerelda",
    favoriteFood: "carrots",
    show: "Our Flag Means Death",
  },
  {
    animal: "lion",
    firstName: "Pash",
    favoriteFood: "burger",
    show: "Bojack Horseman",
  },
  {
    animal: "parrot",
    firstName: "Peri",
    favoriteFood: "couscous",
    show: "Jeopardy",
  },
  {
    animal: "wolf",
    firstName: "Wolfie",
    middleName: "Leopold",
    favoriteFood: "french fries",
    show: "The Good Place",
  },
  {
    animal: "deer",
    firstName: "Lily",
    middleName: "Jane",
    show: "Amazing Race",
    favoriteFood: "pizza",
  },
  {
    animal: "bunny",
    firstName: "Buns",
    middleName: "Bunner",
    show: "Survivor",
  },
  {
    animal: "horse",
    firstName: "Royal",
    middleName: "King",
    show: "Slow Horses",
  },
];
